"""Generate src/unicode_tables.zig: codepoint ranges for the character classes
used by the Qwen2 pretokenizer regex (\\p{L}, \\p{N}, \\s), extracted from the
`regex` module so they match transformers' slow tokenizer exactly.

Run with ComfyUI's venv python:
  ~/genai/comfyui/venv/bin/python tools/gen_unicode_tables.py > src/unicode_tables.zig
"""
import regex

def ranges_for(pattern):
    m = regex.compile(pattern)
    ranges, start, prev = [], None, None
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            hit = False
        else:
            hit = m.match(chr(cp)) is not None
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, 0x10FFFF))
    return ranges

def emit(name, ranges):
    print(f"pub const {name} = [_]Range{{")
    for a, b in ranges:
        print(f"    .{{ .lo = 0x{a:x}, .hi = 0x{b:x} }},")
    print("};\n")

print("//! Unicode range tables for the Qwen2 pretokenizer, generated by")
print("//! tools/gen_unicode_tables.py from the python `regex` module —")
print("//! do not edit by hand.\n")
print("pub const Range = struct { lo: u21, hi: u21 };\n")
emit("letter_ranges", ranges_for(r"\p{L}"))
emit("number_ranges", ranges_for(r"\p{N}"))
emit("whitespace_ranges", ranges_for(r"\s"))
emit("mark_ranges", ranges_for(r"\p{M}"))
