#!/usr/bin/env python3
"""Reference fixtures for SDXL (CLIP-L + CLIP-G, the LDM UNet with micro-conditioning,
AutoencoderKL).

⚠️ **The reference here is ComfyUI, not diffusers** — deliberately, and it is a
different choice from `gen_sd15_fixtures.py`. Three reasons:

  1. ComfyUI is the **compatibility target**: this engine's renders are verified
     pixel-identical to ComfyUI's, so a fixture generated by it pins the thing we
     actually promise.
  2. SDXL's second text tower is stored in **OpenCLIP** naming with a fused
     `attn.in_proj_weight`, and its conditioning is the **penultimate** hidden state
     with the final LayerNorm *skipped*. Those are conventions, not derivable from
     the checkpoint, and ComfyUI owns the ones the ecosystem uses. Hand-converting
     the state dict inside the generator would mean the fixture and the
     implementation under test shared an assumption — exactly what a fixture exists
     to prevent.
  3. The `y` micro-conditioning vector (pooled ++ six 256-d sinusoids) has an
     ordering that only the reference can settle.

Driven headless with ComfyUI's own loader (`comfy.sd.load_checkpoint_guess_config`),
forced to fp32 throughout: the checkpoint stores f16, ComfyUI would infer f16 compute,
and a reference rounding at 1e-3 cannot check an implementation to 1e-3.

Two outputs:

  1. **Tokenizer** (`src/core/assets/clip_tokenizer/fixtures_sdxl.json`, a few KB,
     ungated). SDXL tokenizes each prompt **twice**: CLIP-L pads with `<|endoftext|>`
     and CLIP-G pads with id 0 (`"!"`). Same vocabulary, same merges, different pad —
     and the pad slots are part of the 77-token window the UNet cross-attends to, so
     the difference is not cosmetic. Needs no checkpoint.

  2. **Model parity** (`src/models/assets/sdxl_ref.safetensors`, ~4 MB, gated).
     A real single-file SDXL checkpoint driven through ComfyUI: ids -> the 2048-wide
     concatenated context and the projected pooled vector, (latent, t, context, y) ->
     eps, latent -> RGB. Per-stage (mean, l2, max) triples after every one of the 19
     `input_blocks`/`middle_block`/`output_blocks` — LDM's own decomposition, which is
     also this engine's, so a mismatch localizes to a block.

⚠️ Tied to ONE checkpoint by name and sha256; the Zig test asserts the hash.

Usage (ComfyUI's `nvenv`, NOT the ai-toolkit venv):
    /home/qt/genai/comfyui/nvenv/bin/python tools/gen_sdxl_fixtures.py
"""

import argparse
import hashlib
import json
import os
import sys

COMFY = "/home/qt/genai/comfyui"
DEFAULT_CKPT = os.path.join(COMFY, "models/checkpoints/sdxl/blackMAGICXL_v145.safetensors")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# `tp_core` is rooted at src/core/core.zig and can only `@embedFile` under its own
# path, hence a tokenizer fixture separate from the model one. A separate file from
# SD1.5's rather than a new key in it: two generators writing one JSON would make
# each one's output depend on the other having been run.
TOK_OUT = os.path.join(REPO, "src", "core", "assets", "clip_tokenizer", "fixtures_sdxl.json")
REF_OUT = os.path.join(REPO, "src", "models", "assets", "sdxl_ref.safetensors")

# Fixed everywhere: the fixtures must be reproducible byte-for-byte from this script.
SEED = 20260801
PROMPTS = [
    "a photograph of an astronaut riding a horse",
    "",  # the unconditional branch — CFG needs it, and an empty prompt is not a no-op
]
# 128x128 image => 16x16 latent, and 512x512 => 64. The small case keeps the fixture
# small; the big one is what catches scale-dependent bugs (im2col banding, attention
# over 1024 positions instead of 64) — see the SD1.5 generator's note about a
# 4-latent-pixel checkerboard that reached a rendered image.
LATENT = 16
BIG = 64
VAE_LATENT = 8
VAE_BIG = 64
# The micro-conditioning the fixture is generated with. ComfyUI's own defaults for a
# render of this size: original size == target size == the image, no crop.
MICRO = dict(width=BIG * 8, height=BIG * 8, crop_w=0, crop_h=0,
             target_width=BIG * 8, target_height=BIG * 8)

# ⚠️ ComfyUI parses argv at import time and rejects anything it does not recognize, so
# our own flags have to be taken off `sys.argv` before `import comfy.*` and parsed from
# the saved copy instead. `--cpu` for determinism (no GPU reduction order in a
# reference) and `--fp32-vae` because the SDXL VAE is the fp16-unstable one.
OUR_ARGV = sys.argv[1:]
# ⚠️ `--disable-xformers` is not a performance knob here: ComfyUI binds its attention
# implementation at import time and prefers xformers, which has no CPU fp32 kernel and
# raises from inside the UNet's first SpatialTransformer. `--use-pytorch-cross-attention`
# alone does not displace it — xformers is checked first.
sys.argv = [sys.argv[0], "--cpu", "--fp32-vae", "--disable-smart-memory",
            "--disable-xformers", "--use-pytorch-cross-attention"]
sys.path.insert(0, COMFY)
# ComfyUI resolves its model/tokenizer paths relative to its own root.
os.chdir(COMFY)

# ⚠️ **Imported as a library, ComfyUI ignores argv entirely** — `comfy/cli_args.py`
# parses `[]` unless `comfy.options.enable_args_parsing()` has been called (its `main.py`
# does that first thing). Without this, every flag above is silently a default: the
# reference runs on the GPU with xformers, and there is no diagnostic saying so. The
# assert below is the point — a reference that quietly changed configuration would
# invalidate every number in the fixture with nothing to show for it.
import comfy.options  # noqa: E402

comfy.options.enable_args_parsing()

import torch  # noqa: E402
from comfy.cli_args import args as comfy_args  # noqa: E402
import comfy.model_management as _mm  # noqa: E402

if not (comfy_args.cpu and comfy_args.disable_xformers and comfy_args.fp32_vae):
    raise SystemExit("ComfyUI did not take our flags — check comfy.options.enable_args_parsing()")
if _mm.xformers_enabled():
    raise SystemExit("xformers is still active; it has no CPU fp32 attention kernel")


def stats(t: torch.Tensor) -> list:
    """(mean, l2, max_abs) — the localizing triple for a tensor too big to store."""
    f = t.detach().float().reshape(-1)
    return [float(f.mean()), float(f.norm()), float(f.abs().max())]


def gen_tokenizer_fixtures() -> dict:
    """The two paddings, from ComfyUI's own SDXL tokenizer. No checkpoint needed.

    The cases are the SD1.5 set (chosen for where a from-scratch BPE goes wrong:
    casing, digits, punctuation runs, contractions, multi-byte UTF-8, whitespace
    collapsing, truncation at 77) — reused deliberately, so any difference in the
    output is the padding and nothing else.
    """
    import comfy.sdxl_clip

    tok = comfy.sdxl_clip.SDXLTokenizer(embedding_directory=None)
    cases = []
    for text in [
        "a photograph of an astronaut riding a horse",
        "",
        "A PHOTOGRAPH Of An ASTRONAUT",
        "1girl, 2boys, 42 dogs",
        "hello!!! world???  ...ok",
        "don't can't it's they're",
        "café naïve 中文 \U0001f600",
        "   leading and    collapsing\twhitespace\n",
        "masterpiece, best quality, highly detailed, " + "very " * 60 + "long prompt",
        "sks a<b>c_d-e/f\\g",
    ]:
        t = tok.tokenize_with_weights(text)
        ids_l = [int(i) for i, _w in t["l"][0]]
        ids_g = [int(i) for i, _w in t["g"][0]]
        cases.append({"text": text, "ids_l": ids_l, "ids_g": ids_g})
    return {"sdxl_tokenizer": cases}


def load_reference(ckpt: str):
    """ComfyUI's loader, forced to fp32.

    `model_options`/`te_model_options` carry the dtype rather than `--force-fp32`,
    which only steers the *inference* dtype heuristic; the weights themselves are what
    must be fp32 here.
    """
    import comfy.sd

    model, clip, vae, _ = comfy.sd.load_checkpoint_guess_config(
        ckpt, output_vae=True, output_clip=True,
        model_options={"dtype": torch.float32},
        te_model_options={"dtype": torch.float32},
    )
    unet = model.model.diffusion_model.float().eval()
    vae.first_stage_model = vae.first_stage_model.float().eval()
    for tower in (clip.cond_stage_model.clip_l, clip.cond_stage_model.clip_g):
        tower.transformer.float().eval()
    # Assert rather than trust: an f16 reference would silently cap every comparison
    # below at ~1e-3, which is the tolerance the tests use.
    got = unet.input_blocks[0][0].weight.dtype
    if got != torch.float32:
        raise SystemExit(f"UNet weights are {got}, not fp32 — the reference would be its own error floor")
    return model, clip, vae, unet


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", default=DEFAULT_CKPT)
    ap.add_argument("--tokenizer-only", action="store_true")
    args = ap.parse_args(OUR_ARGV)

    tok_fx = gen_tokenizer_fixtures()
    os.makedirs(os.path.dirname(TOK_OUT), exist_ok=True)
    with open(TOK_OUT, "w") as f:
        json.dump(tok_fx, f)
    print(f"wrote {TOK_OUT}")
    if args.tokenizer_only:
        return

    if not os.path.exists(args.checkpoint):
        raise SystemExit(f"checkpoint not found: {args.checkpoint}")
    print("loading reference models (this reads ~7 GB and expands to fp32)...")
    model, clip, vae, unet = load_reference(args.checkpoint)

    out: dict[str, torch.Tensor] = {}
    meta: dict[str, str] = {}

    with torch.no_grad():
        # --- the two text towers ---------------------------------------------
        # ComfyUI tokenizes and encodes one prompt at a time; stacking here keeps the
        # fixture's batch dimension meaning "prompt", as the UNet cases below expect.
        ids_l, ids_g, ctxs, pools = [], [], [], []
        cap = {}

        def grab(name):
            def fn(_m, _i, o):
                t = o[0] if isinstance(o, tuple) else o
                cap.setdefault(name, []).append(t.detach().float().clone())
            return fn

        def grab_in(name):
            """Capture a module's INPUT. Needed for the embedding output, because
            ComfyUI computes the token embedding *outside* `text_model.embeddings` (so
            that textual-inversion vectors can be spliced in) and passes it as
            `embeds=`, which makes a forward hook on that module never fire — the
            embedding output only exists as the encoder's input."""
            def fn(_m, i):
                cap.setdefault(name, []).append(i[0].detach().float().clone())
            return fn

        # CLIP-G is the new code path (32 layers, OpenCLIP naming, fused QKV), so it
        # gets localizers: a wrong positional table or a wrong fused-QKV split shows up
        # at the embedding output or after layer 0, long before the tower's end.
        tm = clip.cond_stage_model.clip_g.transformer.text_model
        handles = [
            tm.encoder.register_forward_pre_hook(grab_in("clip_g.embed_out")),
            tm.encoder.layers[0].register_forward_hook(grab("clip_g.layer0")),
            tm.final_layer_norm.register_forward_hook(grab("clip_g.final_ln")),
        ]
        for text in PROMPTS:
            tokens = clip.tokenize(text)
            ids_l.append([int(i) for i, _w in tokens["l"][0]])
            ids_g.append([int(i) for i, _w in tokens["g"][0]])
            cond, pooled = clip.encode_from_tokens(tokens, return_pooled=True)
            ctxs.append(cond.float())
            pools.append(pooled.float())
        for h in handles:
            h.remove()

        out["clip.tokens_l"] = torch.tensor(ids_l, dtype=torch.int32)
        out["clip.tokens_g"] = torch.tensor(ids_g, dtype=torch.int32)
        # The conditioning the UNet actually cross-attends to: CLIP-L's penultimate
        # hidden state (768) concatenated with CLIP-G's (1280), **neither** passed
        # through its final LayerNorm. f32, because the UNet cases below are fed this
        # exact tensor — storing it f16 would put a 1e-3 difference in the *input* of a
        # comparison whose tolerance is 1e-3.
        context = torch.cat(ctxs, dim=0)
        out["clip.context"] = context
        out["clip.pooled"] = torch.cat(pools, dim=0)
        # f16 for the localizers: they are compared at ~2e-3 relative, and three
        # [2,77,1280] f32 tensors would double the fixture.
        for k in ("clip_g.embed_out", "clip_g.layer0", "clip_g.final_ln"):
            out[k] = torch.cat(cap[k], dim=0).half()

        # --- the micro-conditioning vector ------------------------------------
        # `y` = pooled(1280) ++ 6 x 256 sinusoids of (h, w, crop_h, crop_w, target_h,
        # target_w) in that order. The order is the whole content of this fixture:
        # every permutation is a valid-looking 2816-vector, and SDXL half-absorbs a
        # wrong one as a composition shift rather than an error.
        adm = model.model.encode_adm(pooled_output=out["clip.pooled"], device="cpu", **MICRO)
        out["unet.adm"] = adm.float()
        meta["micro_cond"] = json.dumps(MICRO)

        # --- UNet -------------------------------------------------------------
        g = torch.Generator().manual_seed(SEED)
        latent = torch.randn(2, 4, LATENT, LATENT, generator=g)
        t = torch.tensor([250.0, 250.0])
        out["unet.latent"] = latent
        out["unet.timestep"] = t.to(torch.int32)
        out["unet.eps"] = unet(latent, timesteps=t, context=context, y=adm).float()

        # The time path in full: `emb` is 1280 floats upstream of every ResBlock, so a
        # wrong sinusoid convention or a wrong label_emb corrupts the forward uniformly
        # and is otherwise indistinguishable from a bad block.
        from comfy.ldm.modules.diffusionmodules.util import timestep_embedding
        t_emb = timestep_embedding(t, unet.model_channels, repeat_only=False)
        out["unet.temb"] = (unet.time_embed(t_emb) + unet.label_emb(adm)).float()
        # And the time embedding alone, so "the sinusoid is right but label_emb is not"
        # separates from "both are wrong".
        out["unet.temb_time_only"] = unet.time_embed(t_emb).float()

        # Per-stage localizers, over LDM's own block list — which is also this engine's
        # decomposition, so a row maps to exactly one `Stage`.
        #
        # ⚠️ **A forward hook on `input_blocks[i]` never fires.** LDM's blocks are
        # `TimestepEmbedSequential` containers that the UNet does not *call*: it hands
        # each one to `forward_timestep_embed`, which iterates the children and dispatches
        # on their type (a ResBlock takes `emb`, a SpatialTransformer takes `context`).
        # So the interception point is that function, not the modules — and patching it
        # also gets the ordering for free: 9 input blocks, the middle block, 9 output
        # blocks, in call order.
        import comfy.ldm.modules.diffusionmodules.openaimodel as oam

        def stage_stats(x, tt, ctx, y):
            rows, names = [], []
            real = oam.forward_timestep_embed
            n_in = len(unet.input_blocks)
            n_mid = 1

            def patched(ts, *a, **kw):
                o = real(ts, *a, **kw)
                i = len(rows)
                names.append(f"in.{i}" if i < n_in else
                             "mid" if i < n_in + n_mid else f"out.{i - n_in - n_mid}")
                rows.append(stats(o))
                return o

            oam.forward_timestep_embed = patched
            try:
                eps = unet(x, timesteps=tt, context=ctx, y=y).float()
            finally:
                oam.forward_timestep_embed = real
            expect = n_in + n_mid + len(unet.output_blocks)
            if len(rows) != expect:
                raise SystemExit(f"expected {expect} stage rows, captured {len(rows)}")
            return eps, torch.tensor(rows, dtype=torch.float32), ",".join(names)

        _, st, names = stage_stats(latent, t, context, adm)
        out["unet.stage_stats"] = st
        meta["unet.stage_names"] = names

        # A SECOND case at a size images are rendered at, for the scale-dependent bugs
        # the 16x16 case is blind to.
        latent_big = torch.randn(1, 4, BIG, BIG, generator=g)
        eps_big, st_big, names_big = stage_stats(latent_big, t[:1], context[:1], adm[:1])
        out["unet_big.latent"] = latent_big
        out["unet_big.eps"] = eps_big
        out["unet_big.stage_stats"] = st_big
        meta["unet_big.stage_names"] = names_big
        meta["unet_big.latent"] = str(BIG)

        # --- VAE decode -------------------------------------------------------
        # `first_stage_model.decode` directly, not `vae.decode`: the latter also divides
        # by `scale_factor` and clamps to [0,1], and what this pins is the decoder.
        vl = torch.randn(1, 4, VAE_LATENT, VAE_LATENT, generator=g)
        out["vae.latent"] = vl
        out["vae.image"] = vae.first_stage_model.decode(vl).float()
        meta["vae.scaling_factor"] = str(model.model.latent_format.scale_factor)

        vl_big = torch.randn(1, 4, VAE_BIG, VAE_BIG, generator=g)
        out["vae_big.latent"] = vl_big
        out["vae_big.image"] = vae.first_stage_model.decode(vl_big).float().half()

    from safetensors.torch import save_file
    meta["checkpoint"] = os.path.basename(args.checkpoint)
    with open(args.checkpoint, "rb") as f:
        h = hashlib.sha256()
        while chunk := f.read(1 << 22):
            h.update(chunk)
    meta["checkpoint_sha256"] = h.hexdigest()
    meta["seed"] = str(SEED)
    meta["prompts"] = json.dumps(PROMPTS)
    meta["generator"] = "tools/gen_sdxl_fixtures.py"
    meta["reference"] = "ComfyUI (comfy.sd.load_checkpoint_guess_config), fp32"

    os.makedirs(os.path.dirname(REF_OUT), exist_ok=True)
    save_file({k: v.contiguous() for k, v in out.items()}, REF_OUT, metadata=meta)
    total = sum(v.numel() * v.element_size() for v in out.values())
    print(f"wrote {REF_OUT} ({total/1e6:.2f} MB, {len(out)} tensors)")
    print(f"  checkpoint sha256 {meta['checkpoint_sha256'][:16]}…")
    print(f"  stages: {names}")


if __name__ == "__main__":
    sys.exit(main())
