#!/usr/bin/env python3
"""Reference fixtures for the SD1.5 family (CLIP-L text encoder, LDM UNet, AutoencoderKL).

Every number the Zig implementation is checked against comes from an external
reference — `transformers.CLIPTextModel`, `diffusers.UNet2DConditionModel`,
`diffusers.AutoencoderKL` — never from our own code. That is the point: a fixture
generated by the implementation under test proves nothing.

Two tiers, because they answer different questions:

  1. **Ops** (`src/ops/assets/sd15_op_fixtures.json`, a few KB, ungated).
     `F.group_norm` and diffusers' `get_timestep_embedding` on small inputs. No
     checkpoint needed, so these run in the fast suite on any machine.

  2. **Model parity** (`src/models/assets/sd15_ref.safetensors`, ~1 MB, gated).
     A real single-file SD1.5 checkpoint driven through the reference modules:
     token ids -> CLIP hidden states, (latent, t, context) -> eps, latent -> RGB.
     Full tensors where they are small, and per-stage (mean, l2, max) triples where
     they are not, so a mismatch localizes to a block instead of just failing at the
     end. Needs the checkpoint, hence `-Dintegration` + `requireModelFile` on the
     Zig side.

⚠️ The fixture is tied to ONE checkpoint by name and hash. A different SD1.5 finetune
has different weights and every number here changes; the Zig test asserts the hash it
was generated against.

Usage (needs torch + diffusers + transformers, e.g. the ai-toolkit venv):
    python tools/gen_sd15_fixtures.py [--checkpoint PATH]
"""

import argparse
import hashlib
import json
import os
import sys

import numpy as np
import torch
import torch.nn.functional as F

DEFAULT_CKPT = "/home/qt/genai/comfyui/models/checkpoints/sd1.5/perfectdeliberate_v20.safetensors"
# ComfyUI's copy of the CLIP BPE vocabulary — the same data our compatibility target
# tokenizes with, and local, so the tokenizer fixture does not depend on the hub.
COMFY_TOKENIZER = "/home/qt/genai/comfyui/comfy/sd1_tokenizer"

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OPS_OUT = os.path.join(REPO, "src", "ops", "assets", "sd15_op_fixtures.json")
# `tp_core` is a separate module rooted at src/core/core.zig, so it can only embed
# fixtures under its own path — hence a second file rather than one shared blob.
TOK_OUT = os.path.join(REPO, "src", "core", "assets", "clip_tokenizer", "fixtures.json")
REF_OUT = os.path.join(REPO, "src", "models", "assets", "sd15_ref.safetensors")

# Fixed everywhere: the fixtures must be reproducible byte-for-byte from this script.
SEED = 20260801
PROMPTS = [
    "a photograph of an astronaut riding a horse",
    "",  # the unconditional branch — CFG needs it, and an empty prompt is not a no-op
]
# 128x128 image => 16x16 latent. Big enough that all three downsamples are exercised
# (16 -> 8 -> 4 -> 2), small enough that the fixture stays about a megabyte.
LATENT = 16
VAE_LATENT = 8  # decodes to 64x64 RGB


def stats(t: torch.Tensor) -> list:
    """(mean, l2, max_abs) — the localizing triple for a tensor too big to store."""
    f = t.detach().float().reshape(-1)
    return [float(f.mean()), float(f.norm()), float(f.abs().max())]


def gen_op_fixtures() -> tuple:
    """Pure-torch op references. No checkpoint, no diffusers model classes."""
    g = torch.Generator().manual_seed(SEED)
    out = {}

    # GroupNorm: what every ResBlock and the VAE run before each convolution. Channel
    # count and group count are SD's (32 groups), and a non-square spatial shape
    # catches an h/w transposition that a square one would hide.
    cases = []
    for (c, h, w, groups) in [(320, 3, 5, 32), (64, 2, 2, 32), (128, 4, 4, 32)]:
        x = torch.randn(1, c, h, w, generator=g)
        weight = torch.randn(c, generator=g)
        bias = torch.randn(c, generator=g) * 0.1
        y = F.group_norm(x, groups, weight, bias, eps=1e-6)
        cases.append({
            "channels": c, "height": h, "width": w, "groups": groups, "eps": 1e-6,
            # Channel-last, which is how our activations are laid out: [h*w][c].
            "input": x[0].permute(1, 2, 0).reshape(-1).tolist(),
            "weight": weight.tolist(),
            "bias": bias.tolist(),
            "expected": y[0].permute(1, 2, 0).reshape(-1).tolist(),
        })
    out["group_norm"] = cases

    # Sinusoidal timestep embedding, in diffusers' exact convention — which differs
    # from the "obvious" one in two ways that silently produce a plausible-looking
    # wrong embedding: the sin/cos halves are concatenated cos-first only when
    # `flip_sin_to_cos`, and the frequency exponent divides by (half_dim -
    # downscale_freq_shift), not half_dim.
    from diffusers.models.embeddings import get_timestep_embedding
    te = []
    for t in [0, 1, 250, 999]:
        emb = get_timestep_embedding(
            torch.tensor([t]), 320, flip_sin_to_cos=True, downscale_freq_shift=0,
        )
        te.append({"timestep": t, "dim": 320, "expected": emb[0].tolist()})
    out["timestep_embedding"] = te

    # CLIP BPE tokenization. The reference is `transformers.CLIPTokenizer` over
    # ComfyUI's own vocab/merges, and the cases are chosen for the places a
    # from-scratch BPE goes wrong rather than for coverage of ordinary words:
    # casing (CLIP lowercases), digits (split per character), punctuation runs,
    # contractions (a dedicated regex branch), multi-byte UTF-8, collapsing
    # whitespace, and a prompt long enough to truncate at 77.
    from transformers import CLIPTokenizer
    tok = CLIPTokenizer.from_pretrained(COMFY_TOKENIZER)
    cases = []
    for text in [
        "a photograph of an astronaut riding a horse",
        "",
        "A PHOTOGRAPH Of An ASTRONAUT",
        "1girl, 2boys, 42 dogs",
        "hello!!! world???  ...ok",
        "don't can't it's they're",
        "caf\u00e9 na\u00efve \u4e2d\u6587 \U0001f600",
        "   leading and    collapsing\twhitespace\n",
        "masterpiece, best quality, highly detailed, " + "very " * 60 + "long prompt",
        "sks a<b>c_d-e/f\\g",
    ]:
        ids = tok(text, padding="max_length", max_length=77, truncation=True).input_ids
        cases.append({"text": text, "ids": ids})
    return out, {"clip_tokenizer": cases}


def load_reference_models(ckpt: str):
    from diffusers import UNet2DConditionModel, AutoencoderKL
    from transformers import CLIPTextModel, CLIPTextConfig, CLIPTokenizer
    from safetensors.torch import load_file

    unet = UNet2DConditionModel.from_single_file(ckpt, torch_dtype=torch.float32).eval()
    vae = AutoencoderKL.from_single_file(ckpt, torch_dtype=torch.float32).eval()

    # CLIP-L is assembled locally rather than fetched: the config below is SD1.5's
    # text tower, and the weights come straight out of the checkpoint under the
    # `cond_stage_model.transformer.` prefix, which is already CLIPTextModel's layout.
    sd = load_file(ckpt)
    prefix = "cond_stage_model.transformer."
    text_sd = {k[len(prefix):]: v for k, v in sd.items() if k.startswith(prefix)}
    text_sd.pop("text_model.embeddings.position_ids", None)
    cfg = CLIPTextConfig(
        vocab_size=49408, hidden_size=768, intermediate_size=3072,
        num_hidden_layers=12, num_attention_heads=12, max_position_embeddings=77,
        hidden_act="quick_gelu", layer_norm_eps=1e-5,
    )
    clip = CLIPTextModel(cfg).eval()
    missing, unexpected = clip.load_state_dict(text_sd, strict=False)
    missing = [m for m in missing if "position_ids" not in m]
    if missing or unexpected:
        raise SystemExit(f"CLIP state dict mismatch: missing={missing[:5]} unexpected={unexpected[:5]}")

    # ⚠️ From the DIRECTORY, not from vocab+merges alone. Constructing CLIPTokenizer
    # from the two data files skips `tokenizer_config.json` / `special_tokens_map.json`,
    # so bos/eos/pad/unk are unset and every word tokenizes to the unknown id — ids
    # that look like a tensor of the right shape and encode nothing. (Caught by the
    # pooled-output lookup finding no eos; the hidden-state comparison passed happily,
    # because both sides were fed the same garbage.)
    tok = CLIPTokenizer.from_pretrained(COMFY_TOKENIZER)
    return unet, vae, clip, tok, sd


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", default=DEFAULT_CKPT)
    ap.add_argument("--ops-only", action="store_true")
    args = ap.parse_args()

    ops_fx, tok_fx = gen_op_fixtures()
    os.makedirs(os.path.dirname(OPS_OUT), exist_ok=True)
    with open(OPS_OUT, "w") as f:
        json.dump(ops_fx, f)
    print(f"wrote {OPS_OUT}")
    os.makedirs(os.path.dirname(TOK_OUT), exist_ok=True)
    with open(TOK_OUT, "w") as f:
        json.dump(tok_fx, f)
    print(f"wrote {TOK_OUT}")
    if args.ops_only:
        return

    if not os.path.exists(args.checkpoint):
        raise SystemExit(f"checkpoint not found: {args.checkpoint}")
    print("loading reference models (this reads ~5 GB)...")
    unet, vae, clip, tok, sd = load_reference_models(args.checkpoint)

    out: dict[str, torch.Tensor] = {}
    meta: dict[str, str] = {}

    with torch.no_grad():
        # --- CLIP-L -----------------------------------------------------------
        ids = tok(PROMPTS, padding="max_length", max_length=77, truncation=True,
                  return_tensors="pt").input_ids
        enc = clip(ids, output_hidden_states=True)
        out["clip.tokens"] = ids.to(torch.int32)
        out["clip.hidden"] = enc.last_hidden_state.float()       # [2, 77, 768]
        out["clip.pooled"] = enc.pooler_output.float()           # [2, 768]
        # hidden_states[0] is the embedding output, [1] is after encoder layer 0 —
        # the two places a wrong positional embedding or a wrong causal mask shows up.
        out["clip.embed_out"] = enc.hidden_states[0].float()
        out["clip.layer0"] = enc.hidden_states[1].float()
        context = enc.last_hidden_state.float()

        # --- UNet -------------------------------------------------------------
        g = torch.Generator().manual_seed(SEED)
        latent = torch.randn(2, 4, LATENT, LATENT, generator=g)
        t = torch.tensor([250, 250])
        eps = unet(latent, t, encoder_hidden_states=context).sample.float()
        out["unet.latent"] = latent
        out["unet.timestep"] = t.to(torch.int32)
        out["unet.eps"] = eps

        # The time path, in full: it is 1280 floats and it is upstream of every block,
        # so a wrong embedding convention corrupts the whole forward uniformly and is
        # otherwise indistinguishable from a bad block.
        from diffusers.models.embeddings import get_timestep_embedding
        t_emb = get_timestep_embedding(t, 320, flip_sin_to_cos=True, downscale_freq_shift=0)
        out["unet.temb"] = unet.time_embedding(t_emb).float()

        # Per-stage localizers: (mean, l2, max_abs) after each down block, the mid
        # block, and each up block. Hooks read the reference's own module outputs, so
        # this is the reference's decomposition, not our guess at one.
        stage_rows: list[list[float]] = []
        stage_names: list[str] = []

        def hook(name):
            def fn(_m, _i, o):
                tensor = o[0] if isinstance(o, tuple) else o
                stage_names.append(name)
                stage_rows.append(stats(tensor))
            return fn

        handles = []
        for i, blk in enumerate(unet.down_blocks):
            handles.append(blk.register_forward_hook(hook(f"down.{i}")))
        handles.append(unet.mid_block.register_forward_hook(hook("mid")))
        for i, blk in enumerate(unet.up_blocks):
            handles.append(blk.register_forward_hook(hook(f"up.{i}")))
        unet(latent, t, encoder_hidden_states=context)
        for h in handles:
            h.remove()
        out["unet.stage_stats"] = torch.tensor(stage_rows, dtype=torch.float32)
        meta["unet.stage_names"] = ",".join(stage_names)

        # A SECOND UNet case at the resolution images are actually rendered at.
        # ⚠️ The 16x16 case above cannot catch a scale-dependent bug: at that size
        # `ops.conv`'s im2col runs in a single band and self-attention sees 256
        # positions, where a real 512x512 render bands 3+ ways and attends over 4096.
        # A grid artifact with a 4-latent-pixel period got all the way to a rendered
        # image before this existed.
        big = 64
        latent_big = torch.randn(1, 4, big, big, generator=g)
        stage_rows_big: list[list[float]] = []
        stage_names_big: list[str] = []

        def hook_big(name):
            def fn(_m, _i, o):
                tensor = o[0] if isinstance(o, tuple) else o
                stage_names_big.append(name)
                stage_rows_big.append(stats(tensor))
            return fn

        handles = []
        for i, blk in enumerate(unet.down_blocks):
            handles.append(blk.register_forward_hook(hook_big(f"down.{i}")))
        handles.append(unet.mid_block.register_forward_hook(hook_big("mid")))
        for i, blk in enumerate(unet.up_blocks):
            handles.append(blk.register_forward_hook(hook_big(f"up.{i}")))
        eps_big = unet(latent_big, t[:1], encoder_hidden_states=context[:1]).sample.float()
        for h in handles:
            h.remove()
        out["unet_big.latent"] = latent_big
        out["unet_big.eps"] = eps_big
        out["unet_big.stage_stats"] = torch.tensor(stage_rows_big, dtype=torch.float32)
        meta["unet_big.stage_names"] = ",".join(stage_names_big)
        meta["unet_big.latent"] = str(big)

        # --- VAE decode -------------------------------------------------------
        vl = torch.randn(1, 4, VAE_LATENT, VAE_LATENT, generator=g)
        img = vae.decode(vl).sample.float()
        out["vae.latent"] = vl
        out["vae.image"] = img
        meta["vae.scaling_factor"] = str(vae.config.scaling_factor)

        # And a decode at the size images are actually rendered at. ⚠️ The 8x8 case
        # above leaves the VAE's convolutions in a single im2col band and its mid-block
        # attention at 64 positions; a 512x512 decode bands up to 512 ways and attends
        # over 4096. Stored f16 to keep the fixture ~1.5 MB — far more precision than a
        # 1e-3 relative comparison needs.
        vl_big = torch.randn(1, 4, 64, 64, generator=g)
        out["vae_big.latent"] = vl_big
        out["vae_big.image"] = vae.decode(vl_big).sample.float().half()

        # --- Scheduler --------------------------------------------------------
        # The betas SD1.5 was trained with (scaled_linear), and the sigma ladder they
        # imply. A sampler that gets these wrong is measuring a different model.
        betas = torch.linspace(0.00085 ** 0.5, 0.012 ** 0.5, 1000, dtype=torch.float64) ** 2
        alphas_cumprod = torch.cumprod(1.0 - betas, dim=0)
        out["sched.alphas_cumprod"] = alphas_cumprod.float()
        sigmas = ((1 - alphas_cumprod) / alphas_cumprod) ** 0.5
        out["sched.sigmas_full"] = sigmas.float()

        # The N-step ladder and its timesteps, from diffusers' own scheduler — the
        # part that is fiddly (evenly spaced in *index*, descending, interpolated,
        # with a trailing zero) and that a hand-rolled version gets subtly wrong.
        from diffusers import EulerDiscreteScheduler
        # ⚠️ `timestep_spacing` is not a detail: "leading" (the old PNDM
        # discretization) starts a 4-step run at **sigma 4.12** instead of 14.615, so
        # the sampler is told the latent is only moderately noisy while it was
        # initialized as pure noise — global structure never forms and the image comes
        # out as noise-textured mush. "linspace" (999 -> 0) is what k-diffusion Euler
        # uses for SD1.5, and what ComfyUI/A1111 sample with.
        sched = EulerDiscreteScheduler(
            beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear",
            num_train_timesteps=1000, steps_offset=0, timestep_spacing="linspace",
        )
        for n in (4, 10):
            sched.set_timesteps(n)
            out[f"sched.sigmas_{n}"] = sched.sigmas.float().clone()
            out[f"sched.timesteps_{n}"] = sched.timesteps.float().clone()

    from safetensors.torch import save_file
    meta["checkpoint"] = os.path.basename(args.checkpoint)
    with open(args.checkpoint, "rb") as f:
        h = hashlib.sha256()
        while chunk := f.read(1 << 22):
            h.update(chunk)
    meta["checkpoint_sha256"] = h.hexdigest()
    meta["seed"] = str(SEED)
    meta["prompts"] = json.dumps(PROMPTS)
    meta["generator"] = "tools/gen_sd15_fixtures.py"

    os.makedirs(os.path.dirname(REF_OUT), exist_ok=True)
    save_file({k: v.contiguous() for k, v in out.items()}, REF_OUT, metadata=meta)
    total = sum(v.numel() * v.element_size() for v in out.values())
    print(f"wrote {REF_OUT} ({total/1e6:.2f} MB, {len(out)} tensors)")
    print(f"  checkpoint sha256 {meta['checkpoint_sha256'][:16]}…")
    print(f"  stages: {meta['unet.stage_names']}")


if __name__ == "__main__":
    sys.exit(main())
