#!/usr/bin/env python3
"""Emit src/gpu/kernels/iq_grid.zig: the ggml IQ codebook tables, flattened.

The four IQ formats this repo reads (iq2_xxs, iq2_xs, iq3_xxs, iq3_s) decode a
stored index into a group of values through a fixed table, and the signs through
a second one. Nothing about either is derivable, so they are taken from ggml by
COMPILING its header and printing what it defines, not by re-typing the digits.

Run with the path to a ggml checkout's src/ggml-common.h, or with nothing, in
which case the ggml package the build already fetched is searched for.

  python3 tools/gen_iq_grid.py [path/to/ggml-common.h]
"""

import hashlib
import pathlib
import subprocess
import sys
import tempfile

# name, C element type, count, bytes per element
TABLES = [
    ("ksigns_iq2xs", "uint8_t", 128, 1),
    # iq4_nl's 16 signed levels, which iq4_nl and iq4_xs index with a nibble.
    # A table rather than a switch because eight switch lookups per group cost
    # those two kernels 2x (measured, `vk-gemv-bench`), while sixteen bytes are
    # one cache line every lane of a subgroup hits.
    ("kvalues_iq4nl", "int8_t", 16, 1),
    ("iq2xxs_grid", "uint64_t", 256, 8),
    ("iq2xs_grid", "uint64_t", 512, 8),
    ("iq3xxs_grid", "uint32_t", 256, 4),
    ("iq3s_grid", "uint32_t", 512, 4),
]

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "gpu" / "kernels" / "iq_grid.zig"


def find_header() -> pathlib.Path:
    if len(sys.argv) > 1:
        return pathlib.Path(sys.argv[1])
    cache = pathlib.Path.home() / ".cache" / "zig" / "p"
    hits = sorted(cache.glob("*/ggml/src/ggml-common.h"))
    if not hits:
        sys.exit("ggml-common.h not found; pass its path (zig build fetches ggml)")
    return hits[-1]


def dump(header: pathlib.Path) -> dict[str, bytes]:
    """Compile a program that includes the header and prints each table's bytes."""
    body = []
    for name, _ctype, count, width in TABLES:
        body.append(f'    printf("{name}");')
        body.append(f"    for (int i = 0; i < {count}; ++i) {{")
        body.append(f"        for (int b = 0; b < {width}; ++b)")
        body.append(
            f'            printf(" %u", (unsigned)((({name}[i]) >> (8*b)) & 0xff));'
        )
        body.append("    }")
        body.append('    printf("\\n");')
    src = (
        "#define GGML_COMMON_IMPL_C\n"
        "#define GGML_COMMON_DECL_C\n"
        f'#include "{header}"\n'
        "#include <stdio.h>\n"
        "int main(void) {\n" + "\n".join(body) + "\n    return 0;\n}\n"
    )
    with tempfile.TemporaryDirectory() as td:
        c = pathlib.Path(td) / "dump.c"
        exe = pathlib.Path(td) / "dump"
        c.write_text(src)
        # The tables are `static const` and most go unused by main; silence that
        # rather than touching the header.
        subprocess.run(
            ["cc", "-O0", "-w", "-o", str(exe), str(c)], check=True
        )
        out = subprocess.run([str(exe)], check=True, capture_output=True, text=True)
    tables = {}
    for line in out.stdout.strip().splitlines():
        parts = line.split()
        tables[parts[0]] = bytes(int(p) for p in parts[1:])
    return tables


def main() -> None:
    header = find_header()
    digest = hashlib.sha256(header.read_bytes()).hexdigest()
    tables = dump(header)

    offsets = {}
    blob = bytearray()
    for name, _ctype, count, width in TABLES:
        data = tables[name]
        assert len(data) == count * width, (name, len(data))
        assert len(blob) % 4 == 0, name  # Env reads the blob as u32 words
        offsets[name] = len(blob)
        blob += data

    rows = []
    for i in range(0, len(blob), 16):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in blob[i : i + 16]))

    consts = "\n".join(
        f"pub const {n}_off: u32 = {offsets[n]};" for n, _c, _k, _w in TABLES
    )
    text = f"""//! ggml's IQ codebook tables, flattened into one byte blob a GPU buffer holds.
//!
//! GENERATED by tools/gen_iq_grid.py from ggml's src/ggml-common.h
//! (sha256 {digest}). Do not edit; re-run the generator.
//!
//! A grid entry is stored little-endian, so entry `i`'s value `j` is byte
//! `i * width + j` of its table, which is how ggml reads it
//! (`(const uint8_t *)(grid + index)`). `ksigns_iq2xs[s]` holds eight sign bits,
//! bit `j` set meaning value `j` is negated (ggml's `kmask_iq2xs[j]` is `1 << j`
//! and is not tabulated here).
//!
//! Both GPU hosts upload this blob once and bind it as the kernels' table slot;
//! the offsets below are what a decoder adds to reach its own table.

{consts}

pub const blob = [_]u8{{
{chr(10).join(rows)}
}};
"""
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(blob)} bytes) from {header}")


if __name__ == "__main__":
    main()
