//! RMS normalization (f32 compute, matching ComfyUI's reference modules).
//!
//! The Krea 2 checkpoints store norm weights zero-centered (`(1 + scale)`
//! convention); Qwen3 stores them directly. Both are handled by dequantizing
//! the *effective* weight at load time, so this op always takes the weight
//! as given. Krea 2 uses eps 1e-5, Qwen3 1e-6.

const std = @import("std");

/// Row-wise RMSNorm over the last dimension: out = x / sqrt(mean(x^2) + eps) * w.
/// `x` is [n_rows, w.len] row-major; `out` may alias `x`.
pub fn rmsNorm(out: []f32, x: []const f32, weight: []const f32, eps: f32) void {
    std.debug.assert(x.len == out.len);
    const dim = weight.len;
    std.debug.assert(x.len % dim == 0);
    var row: usize = 0;
    while (row < x.len) : (row += dim) {
        const xr = x[row..][0..dim];
        const or_ = out[row..][0..dim];
        const inv = invRms(xr, eps);
        for (or_, xr, weight) |*o, xv, wv| o.* = xv * inv * wv;
    }
}

/// Classic LayerNorm with weight and bias, in rows of `weight.len`:
/// out = (x - mean) / sqrt(var + eps) * weight + bias (the qwen3vl vision
/// tower's ln1/ln2/post_ln). `out` may alias `x`.
pub fn layerNorm(out: []f32, x: []const f32, weight: []const f32, bias: []const f32, eps: f32) void {
    std.debug.assert(x.len == out.len and weight.len == bias.len);
    const dim = weight.len;
    std.debug.assert(x.len % dim == 0);
    const dim_f: f32 = @floatFromInt(dim);
    var row: usize = 0;
    while (row < x.len) : (row += dim) {
        const xr = x[row..][0..dim];
        const or_ = out[row..][0..dim];
        var sum: f32 = 0;
        for (xr) |v| sum += v;
        const mean = sum / dim_f;
        var var_sum: f32 = 0;
        for (xr) |v| var_sum += (v - mean) * (v - mean);
        const inv = 1.0 / @sqrt(var_sum / dim_f + eps);
        for (or_, xr, weight, bias) |*o, xv, wv, bv| o.* = (xv - mean) * inv * wv + bv;
    }
}

/// 1 / sqrt(mean(x^2) + eps), with vectorized partial sums.
pub fn invRms(x: []const f32, eps: f32) f32 {
    const vlen = comptime std.simd.suggestVectorLength(f32) orelse 8;
    const Vec = @Vector(vlen, f32);
    var acc: Vec = @splat(0);
    var i: usize = 0;
    while (i + vlen <= x.len) : (i += vlen) {
        const xv: Vec = x[i..][0..vlen].*;
        acc += xv * xv;
    }
    var sum: f32 = @reduce(.Add, acc);
    while (i < x.len) : (i += 1) sum += x[i] * x[i];
    const mean = sum / @as(f32, @floatFromInt(x.len));
    return 1.0 / @sqrt(mean + eps);
}

// Reference values generated by tools/gen_op_fixtures.py (torch 2.6).
const rmsnorm_x = [_]f32{ 0.5, -1.5, 2, 0.25, 3, 0, -0.125, 1 };
const rmsnorm_scale = [_]f32{ 0.100000001, -0.200000003, 0, 0.5 };
const rmsnorm_out = [_]f32{ 0.429394752, -0.936861217, 1.56143546, 0.292769134, 2.08547044, 0, -0.0789950937, 0.947941124 };
const rmsnorm_plain_out = [_]f32{ 0.429395914, -0.93686384, 1.56143963, 0.292769939, 2.08547425, 0, -0.0789952353, 0.947942853 };

test "rmsnorm matches torch" {
    // Effective weight = 1 + scale (the load path adds the 1).
    var weight: [4]f32 = undefined;
    for (&weight, rmsnorm_scale) |*w, s| w.* = 1.0 + s;

    var out: [8]f32 = undefined;
    rmsNorm(&out, &rmsnorm_x, &weight, 1e-5);
    for (rmsnorm_out, out) |e, a| try std.testing.expectApproxEqAbs(e, a, 2e-6);

    // Same weights at Qwen's eps.
    rmsNorm(&out, &rmsnorm_x, &weight, 1e-6);
    for (rmsnorm_plain_out, out) |e, a| try std.testing.expectApproxEqAbs(e, a, 2e-6);
}

test "rmsnorm in place and odd dims" {
    // dim 5 exercises the scalar tail; out aliases x.
    var x = [_]f32{ 1, 2, 3, 4, 5, -1, -2, -3, -4, -5 };
    const w = [_]f32{ 1, 1, 1, 1, 1 };
    rmsNorm(&x, &x, &w, 0.0);
    const rms = @sqrt(@as(f32, 55.0 / 5.0));
    try std.testing.expectApproxEqAbs(@as(f32, 1.0 / rms), x[0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, -5.0 / rms), x[9], 1e-6);
}
