//! RMS normalization (f32 compute, matching ComfyUI's reference modules).
//!
//! The Krea 2 checkpoints store norm weights zero-centered (`(1 + scale)`
//! convention); Qwen3 stores them directly. Both are handled by dequantizing
//! the *effective* weight at load time, so this op always takes the weight
//! as given. Krea 2 uses eps 1e-5, Qwen3 1e-6.

const std = @import("std");

/// Row-wise RMSNorm over the last dimension: out = x / sqrt(mean(x^2) + eps) * w.
/// `x` is [n_rows, w.len] row-major; `out` may alias `x`.
pub fn rmsNorm(out: []f32, x: []const f32, weight: []const f32, eps: f32) void {
    std.debug.assert(x.len == out.len);
    const dim = weight.len;
    std.debug.assert(x.len % dim == 0);
    var row: usize = 0;
    while (row < x.len) : (row += dim) {
        const xr = x[row..][0..dim];
        const or_ = out[row..][0..dim];
        const inv = invRms(xr, eps);
        for (or_, xr, weight) |*o, xv, wv| o.* = xv * inv * wv;
    }
}

/// Row-wise RMSNorm with no learned weight: out = x / sqrt(mean(x^2) + eps),
/// in rows of `dim`. `out` may alias `x`. Gemma 4 normalizes V this way (a
/// weightless RMS over head_dim, unlike its weighted Q/K norms).
pub fn rmsNormUnit(out: []f32, x: []const f32, dim: usize, eps: f32) void {
    std.debug.assert(x.len == out.len);
    std.debug.assert(dim != 0 and x.len % dim == 0);
    var row: usize = 0;
    while (row < x.len) : (row += dim) {
        const xr = x[row..][0..dim];
        const or_ = out[row..][0..dim];
        const inv = invRms(xr, eps);
        for (or_, xr) |*o, xv| o.* = xv * inv;
    }
}

/// Classic LayerNorm with weight and bias, in rows of `weight.len`:
/// out = (x - mean) / sqrt(var + eps) * weight + bias (the qwen3vl vision
/// tower's ln1/ln2/post_ln). `out` may alias `x`.
pub fn layerNorm(out: []f32, x: []const f32, weight: []const f32, bias: []const f32, eps: f32) void {
    std.debug.assert(x.len == out.len and weight.len == bias.len);
    const dim = weight.len;
    std.debug.assert(x.len % dim == 0);
    const dim_f: f32 = @floatFromInt(dim);
    var row: usize = 0;
    while (row < x.len) : (row += dim) {
        const xr = x[row..][0..dim];
        const or_ = out[row..][0..dim];
        var sum: f32 = 0;
        for (xr) |v| sum += v;
        const mean = sum / dim_f;
        var var_sum: f32 = 0;
        for (xr) |v| var_sum += (v - mean) * (v - mean);
        const inv = 1.0 / @sqrt(var_sum / dim_f + eps);
        for (or_, xr, weight, bias) |*o, xv, wv, bv| o.* = (xv - mean) * inv * wv + bv;
    }
}

/// LayerNorm with **no learned weight or bias** (`elementwise_affine=False`):
/// out = (x - mean) / sqrt(var + eps), in rows of `dim`. `out` may alias `x`.
///
/// Z-Image's `final_layer.norm_final` is this: the affine part is supplied
/// separately by the AdaLN modulation that follows, so the norm itself carries no
/// parameters. Uses the **biased** variance (divide by `n`), like `torch.nn.LayerNorm`.
pub fn layerNormUnit(out: []f32, x: []const f32, dim: usize, eps: f32) void {
    std.debug.assert(x.len == out.len);
    std.debug.assert(dim != 0 and x.len % dim == 0);
    const dim_f: f32 = @floatFromInt(dim);
    var row: usize = 0;
    while (row < x.len) : (row += dim) {
        const xr = x[row..][0..dim];
        const or_ = out[row..][0..dim];
        var sum: f32 = 0;
        for (xr) |v| sum += v;
        const mean = sum / dim_f;
        var var_sum: f32 = 0;
        for (xr) |v| var_sum += (v - mean) * (v - mean);
        const inv = 1.0 / @sqrt(var_sum / dim_f + eps);
        for (or_, xr) |*o, xv| o.* = (xv - mean) * inv;
    }
}

/// 1 / sqrt(mean(x^2) + eps), with vectorized partial sums.
pub fn invRms(x: []const f32, eps: f32) f32 {
    const vlen = comptime std.simd.suggestVectorLength(f32) orelse 8;
    const Vec = @Vector(vlen, f32);
    var acc: Vec = @splat(0);
    var i: usize = 0;
    while (i + vlen <= x.len) : (i += vlen) {
        const xv: Vec = x[i..][0..vlen].*;
        acc += xv * xv;
    }
    var sum: f32 = @reduce(.Add, acc);
    while (i < x.len) : (i += 1) sum += x[i] * x[i];
    const mean = sum / @as(f32, @floatFromInt(x.len));
    return 1.0 / @sqrt(mean + eps);
}

// Reference values generated by tools/gen_op_fixtures.py (torch 2.6).
const rmsnorm_x = [_]f32{ 0.5, -1.5, 2, 0.25, 3, 0, -0.125, 1 };
const rmsnorm_scale = [_]f32{ 0.100000001, -0.200000003, 0, 0.5 };
const rmsnorm_out = [_]f32{ 0.429394752, -0.936861217, 1.56143546, 0.292769134, 2.08547044, 0, -0.0789950937, 0.947941124 };
const rmsnorm_plain_out = [_]f32{ 0.429395914, -0.93686384, 1.56143963, 0.292769939, 2.08547425, 0, -0.0789952353, 0.947942853 };

test "rmsnorm matches torch" {
    // Effective weight = 1 + scale (the load path adds the 1).
    var weight: [4]f32 = undefined;
    for (&weight, rmsnorm_scale) |*w, s| w.* = 1.0 + s;

    var out: [8]f32 = undefined;
    rmsNorm(&out, &rmsnorm_x, &weight, 1e-5);
    for (rmsnorm_out, out) |e, a| try std.testing.expectApproxEqAbs(e, a, 2e-6);

    // Same weights at Qwen's eps.
    rmsNorm(&out, &rmsnorm_x, &weight, 1e-6);
    for (rmsnorm_plain_out, out) |e, a| try std.testing.expectApproxEqAbs(e, a, 2e-6);
}

test "rmsnorm in place and odd dims" {
    // dim 5 exercises the scalar tail; out aliases x.
    var x = [_]f32{ 1, 2, 3, 4, 5, -1, -2, -3, -4, -5 };
    const w = [_]f32{ 1, 1, 1, 1, 1 };
    rmsNorm(&x, &x, &w, 0.0);
    const rms = @sqrt(@as(f32, 55.0 / 5.0));
    try std.testing.expectApproxEqAbs(@as(f32, 1.0 / rms), x[0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, -5.0 / rms), x[9], 1e-6);
}

/// GroupNorm over channel-last activations: `x` is `[n_positions][channels]`, and
/// each group of `channels / groups` **adjacent channels** is normalized over its own
/// mean and variance **across all positions**. `out` may alias `x`.
///
/// This is what every SD-family ResBlock and VAE block runs before its convolution,
/// and it is the one normalization in this codebase whose statistics are **not**
/// per-position. RMSNorm and LayerNorm reduce along the row a position owns;
/// GroupNorm reduces over `h·w·(channels/groups)` values at once. Laying activations
/// out channel-last therefore makes its access pattern strided, which is why this
/// takes a whole activation rather than a row.
///
/// ⚠️ **Biased variance, matching `torch.nn.functional.group_norm`** — divide by `n`,
/// never `n − 1`. With 32 groups over a 320-channel 8×8 activation that is 640 values
/// per group, so the difference is ~0.08% of the variance: far too small to look like
/// a bug and far too large to leave to chance in a 25-block network.
pub fn groupNorm(
    out: []f32,
    x: []const f32,
    channels: usize,
    groups: usize,
    weight: []const f32,
    bias: []const f32,
    eps: f32,
) void {
    std.debug.assert(out.len == x.len);
    std.debug.assert(channels != 0 and groups != 0 and channels % groups == 0);
    std.debug.assert(x.len % channels == 0);
    std.debug.assert(weight.len == channels and bias.len == channels);

    const positions = x.len / channels;
    const per_group = channels / groups;

    var g: usize = 0;
    while (g < groups) : (g += 1) {
        const c0 = g * per_group;
        // Two passes over the group rather than a sum/sum-of-squares single pass: the
        // shifted form loses catastrophically when the mean is large relative to the
        // spread, which is exactly the regime a late VAE block sits in.
        var sum: f64 = 0;
        var p: usize = 0;
        while (p < positions) : (p += 1) {
            const row = x[p * channels ..][c0..][0..per_group];
            for (row) |v| sum += v;
        }
        const n: f64 = @floatFromInt(positions * per_group);
        const mean = sum / n;

        var sq: f64 = 0;
        p = 0;
        while (p < positions) : (p += 1) {
            const row = x[p * channels ..][c0..][0..per_group];
            for (row) |v| {
                const d = @as(f64, v) - mean;
                sq += d * d;
            }
        }
        const inv = 1.0 / @sqrt(sq / n + @as(f64, eps));

        const meanf: f32 = @floatCast(mean);
        const invf: f32 = @floatCast(inv);
        p = 0;
        while (p < positions) : (p += 1) {
            const src = x[p * channels ..][c0..][0..per_group];
            const dst = out[p * channels ..][c0..][0..per_group];
            for (dst, src, weight[c0..][0..per_group], bias[c0..][0..per_group]) |*o, v, wv, bv| {
                o.* = (v - meanf) * invf * wv + bv;
            }
        }
    }
}

// --- SD-family fixture tests ------------------------------------------------

const sd15_op_fixtures_json = @embedFile("assets/sd15_op_fixtures.json");

const GroupNormCase = struct {
    channels: usize,
    height: usize,
    width: usize,
    groups: usize,
    eps: f32,
    /// `[h*w][channels]`, channel-last — our layout, not torch's.
    input: []const f32,
    weight: []const f32,
    bias: []const f32,
    expected: []const f32,
};

const Sd15OpFixtures = struct { group_norm: []const GroupNormCase };

test "groupNorm matches torch.nn.functional.group_norm" {
    const gpa = std.testing.allocator;
    var parsed = try std.json.parseFromSlice(
        Sd15OpFixtures,
        gpa,
        sd15_op_fixtures_json,
        .{ .ignore_unknown_fields = true },
    );
    defer parsed.deinit();

    for (parsed.value.group_norm) |c| {
        const out = try gpa.alloc(f32, c.input.len);
        defer gpa.free(out);
        groupNorm(out, c.input, c.channels, c.groups, c.weight, c.bias, c.eps);
        for (c.expected, out, 0..) |e, a, i| {
            errdefer std.debug.print(
                "group_norm c={d} h={d} w={d}: index {d} expected {d:.6} got {d:.6}\n",
                .{ c.channels, c.height, c.width, i, e, a },
            );
            try std.testing.expectApproxEqAbs(e, a, 2e-5);
        }
    }
}

test "groupNorm normalizes each group independently and in place" {
    // Two groups whose scales differ by 100x: if the statistics leaked across groups
    // the small group would come out near zero instead of unit-variance. `out` aliases
    // `x`, which every caller in the ResBlock path relies on.
    var x = [_]f32{ 1, 2, 100, 200, 3, 4, 300, 400 }; // [4 positions][... ] see below
    // 4 channels, 2 groups: channels 0,1 are group 0 (small), 2,3 are group 1 (large).
    const w = [_]f32{ 1, 1, 1, 1 };
    const b = [_]f32{ 0, 0, 0, 0 };
    groupNorm(&x, &x, 4, 2, &w, &b, 0);

    var g0: f64 = 0;
    var g1: f64 = 0;
    for ([_]usize{ 0, 1, 4, 5 }) |i| g0 += x[i] * x[i];
    for ([_]usize{ 2, 3, 6, 7 }) |i| g1 += x[i] * x[i];
    // Zero mean removed, unit variance imposed: sum of squares == count, per group.
    try std.testing.expectApproxEqAbs(@as(f64, 4), g0, 1e-4);
    try std.testing.expectApproxEqAbs(@as(f64, 4), g1, 1e-4);
}
